name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm install -g codecov
        npm run render:build --if-present
        npm run main:build
        npm run test
        codecov -t 792fa87c-d976-4bfe-8857-9780072c08fc
      env:
        CI: true
